version: '3'
services:
  mongodb:
    image : mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=password 
  mongo-ui:
    image : mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password 
      - ME_CONFIG_MONGODB_SERVER=mongodb 
    depends_on:
      - mongodb
  my_app:
    build : .
    ports:
      - 8080:3000
    depends_on:
      - mongodb
    volumes:
      - .:/node_app
      - /node_app/node_modules
      